### ISSUE TITLE
没有数据库文件waterv4.mdf

### ISSUE THREAD

**Issue by 18611537517** [neozhu/iot_water#3]
WebApp项目的App_data目录下没有waterv4.mdf

**Comment by neozhu** [comment]
这个项目是code-frist模式，你可以用代码生成新的库

**Comment by 18611537517** [comment]
感谢回复，我研究一下

**Comment by 18611537517** [comment]
这些表创建不了，没有相关的语句啊！

            CreateIndex("dbo.Companies", "TenantId");
            CreateIndex("dbo.Departments", "TenantId");
            CreateIndex("dbo.Employees", "TenantId");
            CreateIndex("dbo.CodeItems", "TenantId");
            
            CreateIndex("dbo.DataTableImportMappings", "TenantId");
            CreateIndex("dbo.Logs", "TenantId");
           
            CreateIndex("dbo.MenuItems", "TenantId");
            CreateIndex("dbo.Notifications", "TenantId");
            
            CreateIndex("dbo.RoleMenus", "TenantId");
