### ISSUE TITLE
这些表创建不了，没有相关的语句啊！

### ISSUE THREAD

**Issue by 18611537517** [neozhu/iot_water#4]
这些表创建不了，没有相关的语句啊！

        CreateIndex("dbo.Companies", "TenantId");
        CreateIndex("dbo.Departments", "TenantId");
        CreateIndex("dbo.Employees", "TenantId");
        CreateIndex("dbo.CodeItems", "TenantId");
        
        CreateIndex("dbo.DataTableImportMappings", "TenantId");
        CreateIndex("dbo.Logs", "TenantId");
       
        CreateIndex("dbo.MenuItems", "TenantId");
        CreateIndex("dbo.Notifications", "TenantId");
        
        CreateIndex("dbo.RoleMenus", "TenantId");

**Comment by neozhu** [comment]
不好意思，我最近实在没时间support，这种项目也很难直接拿来部署使用的。

**Comment by neozhu** [comment]
其实你可以删除所有migration,然后再生成一个全新的库

**Comment by 18611537517** [comment]
好的，多谢了！
