### ISSUE TITLE
启动提示文件缺失

### ISSUE THREAD

**Issue by liutingView** [neozhu/iot_water#7]
启动构建时发生错误，提示未找到以下文件，是否存在一下文件未上传完毕的情况
>D:\MyProject\other\iot_water-main\src\admin\application\CSC : error CS2001: 未能找到源文件“D:\MyProject\other\iot_water-main\src\admin\application\Repositories\Logs\LogQuery.cs”。
1>D:\MyProject\other\iot_water-main\src\admin\application\CSC : error CS2001: 未能找到源文件“D:\MyProject\other\iot_water-main\src\admin\application\Repositories\Logs\LogRepository.cs”。
1>D:\MyProject\other\iot_water-main\src\admin\application\CSC : error CS2001: 未能找到源文件“D:\MyProject\other\iot_water-main\src\admin\application\Services\Logs\ILogService.cs”。
1>D:\MyProject\other\iot_water-main\src\admin\application\CSC : error CS2001: 未能找到源文件“D:\MyProject\other\iot_water-main\src\admin\application\Services\Logs\LogService.cs”。

**Comment by neozhu** [comment]
这是一个企业项目，我并不打算完全免费开源

**Comment by liutingView** [comment]
你好我想部署一版该项目仅用于原型演示，而非投入生产使用，我应该如何联系您讨论您的收益细则呢？

**Comment by neozhu** [comment]
你可以用我提供的地址做演示
